.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bastoji_qt test_bastoji_qt
clean: FORCE
	$(MAKE) -C .. bastoji_qt_clean test_bastoji_qt_clean
check: FORCE
	$(MAKE) -C .. test_bastoji_qt_check
bastoji-qt bastoji-qt.exe: FORCE
	 $(MAKE) -C .. bastoji_qt
